-- Script para criar tabela de países com bandeiras SVG no Supabase
-- Execute este script no SQL Editor do Supabase

-- Criar tabela de países
CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    flag_code VARCHAR(20) NOT NULL UNIQUE,
    flag_svg TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir países com seus códigos de bandeira
INSERT INTO countries (name, flag_code) VALUES
-- América do Norte
('United States', 'us'),
('Canada', 'ca'),
('Mexico', 'mx'),

-- América do Sul
('Brazil', 'br'),
('Argentina', 'ar'),
('Chile', 'cl'),
('Colombia', 'co'),
('Peru', 'pe'),
('Venezuela', 've'),
('Ecuador', 'ec'),
('Bolivia', 'bo'),
('Paraguay', 'py'),
('Uruguay', 'uy'),
('Guyana', 'gy'),
('Suriname', 'sr'),
('French Guiana', 'gf'),

-- Europa
('England', 'gb-eng'),
('Scotland', 'gb-sct'),
('Wales', 'gb-wls'),
('Northern Ireland', 'gb-nir'),
('Ireland', 'ie'),
('France', 'fr'),
('Germany', 'de'),
('Italy', 'it'),
('Spain', 'es'),
('Portugal', 'pt'),
('Netherlands', 'nl'),
('Belgium', 'be'),
('Switzerland', 'ch'),
('Austria', 'at'),
('Sweden', 'se'),
('Norway', 'no'),
('Denmark', 'dk'),
('Finland', 'fi'),
('Iceland', 'is'),
('Poland', 'pl'),
('Czech Republic', 'cz'),
('Slovakia', 'sk'),
('Hungary', 'hu'),
('Romania', 'ro'),
('Bulgaria', 'bg'),
('Greece', 'gr'),
('Croatia', 'hr'),
('Slovenia', 'si'),
('Serbia', 'rs'),
('Bosnia and Herzegovina', 'ba'),
('Montenegro', 'me'),
('Albania', 'al'),
('North Macedonia', 'mk'),
('Kosovo', 'xk'),
('Moldova', 'md'),
('Ukraine', 'ua'),
('Belarus', 'by'),
('Lithuania', 'lt'),
('Latvia', 'lv'),
('Estonia', 'ee'),
('Russia', 'ru'),
('Georgia', 'ge'),
('Armenia', 'am'),
('Azerbaijan', 'az'),
('Turkey', 'tr'),
('Cyprus', 'cy'),
('Malta', 'mt'),

-- Ásia
('China', 'cn'),
('Japan', 'jp'),
('South Korea', 'kr'),
('North Korea', 'kp'),
('Taiwan', 'tw'),
('Hong Kong', 'hk'),
('Macau', 'mo'),
('Mongolia', 'mn'),
('Vietnam', 'vn'),
('Laos', 'la'),
('Cambodia', 'kh'),
('Thailand', 'th'),
('Myanmar', 'mm'),
('Malaysia', 'my'),
('Singapore', 'sg'),
('Indonesia', 'id'),
('Philippines', 'ph'),
('Brunei', 'bn'),
('East Timor', 'tl'),
('India', 'in'),
('Pakistan', 'pk'),
('Afghanistan', 'af'),
('Iran', 'ir'),
('Iraq', 'iq'),
('Syria', 'sy'),
('Lebanon', 'lb'),
('Jordan', 'jo'),
('Israel', 'il'),
('Saudi Arabia', 'sa'),
('Yemen', 'ye'),
('Oman', 'om'),
('United Arab Emirates', 'ae'),
('Qatar', 'qa'),
('Kuwait', 'kw'),
('Bahrain', 'bh'),
('Uzbekistan', 'uz'),
('Kazakhstan', 'kz'),
('Kyrgyzstan', 'kg'),
('Tajikistan', 'tj'),
('Turkmenistan', 'tm'),
('Bangladesh', 'bd'),
('Sri Lanka', 'lk'),
('Nepal', 'np'),
('Bhutan', 'bt'),
('Maldives', 'mv'),

-- África
('South Africa', 'za'),
('Nigeria', 'ng'),
('Ghana', 'gh'),
('Cameroon', 'cm'),
('Morocco', 'ma'),
('Tunisia', 'tn'),
('Algeria', 'dz'),
('Egypt', 'eg'),
('Kenya', 'ke'),
('Uganda', 'ug'),
('Tanzania', 'tz'),
('Ethiopia', 'et'),
('Somalia', 'so'),
('Sudan', 'sd'),
('South Sudan', 'ss'),
('Eritrea', 'er'),
('Djibouti', 'dj'),
('Comoros', 'km'),
('Madagascar', 'mg'),
('Mauritius', 'mu'),
('Seychelles', 'sc'),
('Reunion', 're'),
('Mayotte', 'yt'),

-- Oceania
('Australia', 'au'),
('New Zealand', 'nz'),
('Papua New Guinea', 'pg'),
('Fiji', 'fj'),
('Vanuatu', 'vu'),
('New Caledonia', 'nc'),
('Solomon Islands', 'sb'),
('Kiribati', 'ki'),
('Tuvalu', 'tv'),
('Nauru', 'nr'),
('Palau', 'pw'),
('Marshall Islands', 'mh'),
('Micronesia', 'fm'),
('Guam', 'gu'),
('Northern Mariana Islands', 'mp'),
('American Samoa', 'as'),
('Cook Islands', 'ck'),
('Niue', 'nu'),
('Tokelau', 'tk'),
('Wallis and Futuna', 'wf'),
('French Polynesia', 'pf'),
('Pitcairn', 'pn'),

-- Caribe e América Central
('Cuba', 'cu'),
('Jamaica', 'jm'),
('Haiti', 'ht'),
('Dominican Republic', 'do'),
('Puerto Rico', 'pr'),
('U.S. Virgin Islands', 'vi'),
('British Virgin Islands', 'vg'),
('Anguilla', 'ai'),
('Saint Kitts and Nevis', 'kn'),
('Antigua and Barbuda', 'ag'),
('Montserrat', 'ms'),
('Guadeloupe', 'gp'),
('Martinique', 'mq'),
('Saint Lucia', 'lc'),
('Saint Vincent and the Grenadines', 'vc'),
('Barbados', 'bb'),
('Grenada', 'gd'),
('Trinidad and Tobago', 'tt'),
('Dominica', 'dm'),
('Saint Martin', 'mf'),
('Sint Maarten', 'sx'),
('Saint Barthélemy', 'bl'),
('Aruba', 'aw'),
('Curaçao', 'cw'),
('Bonaire', 'bq-bo'),
('Sint Eustatius', 'bq-se'),
('Saba', 'bq-sa'),
('Guatemala', 'gt'),
('Belize', 'bz'),
('El Salvador', 'sv'),
('Honduras', 'hn'),
('Nicaragua', 'ni'),
('Costa Rica', 'cr'),
('Panama', 'pa'),

-- Outros territórios importantes
('Falkland Islands', 'fk'),
('South Georgia', 'gs'),
('Antarctica', 'aq'),
('Greenland', 'gl'),
('Faroe Islands', 'fo'),
('Gibraltar', 'gi'),
('Bermuda', 'bm'),
('Cayman Islands', 'ky'),
('Turks and Caicos Islands', 'tc'),
('Bahamas', 'bs'),
('Cape Verde', 'cv'),
('São Tomé and Príncipe', 'st'),
('Equatorial Guinea', 'gq'),
('Gabon', 'ga'),
('Republic of the Congo', 'cg'),
('Democratic Republic of the Congo', 'cd'),
('Central African Republic', 'cf'),
('Chad', 'td'),
('Niger', 'ne'),
('Mali', 'ml'),
('Burkina Faso', 'bf'),
('Senegal', 'sn'),
('Gambia', 'gm'),
('Guinea-Bissau', 'gw'),
('Guinea', 'gn'),
('Sierra Leone', 'sl'),
('Liberia', 'lr'),
('Ivory Coast', 'ci'),
('Togo', 'tg'),
('Benin', 'bj'),
('Mauritania', 'mr'),
('Western Sahara', 'eh'),
('Libya', 'ly'),
('Chad', 'td'),
('Niger', 'ne'),
('Mali', 'ml'),
('Burkina Faso', 'bf'),
('Senegal', 'sn'),
('Gambia', 'gm'),
('Guinea-Bissau', 'gw'),
('Guinea', 'gn'),
('Sierra Leone', 'sl'),
('Liberia', 'lr'),
('Ivory Coast', 'ci'),
('Togo', 'tg'),
('Benin', 'bj'),
('Mauritania', 'mr'),
('Western Sahara', 'eh'),
('Libya', 'ly')
ON CONFLICT (name) DO NOTHING;

-- Criar índice para melhor performance
CREATE INDEX IF NOT EXISTS idx_countries_flag_code ON countries(flag_code);
CREATE INDEX IF NOT EXISTS idx_countries_name ON countries(name);

-- Função para atualizar o timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para atualizar updated_at automaticamente
CREATE TRIGGER update_countries_updated_at 
    BEFORE UPDATE ON countries 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Comentários sobre a tabela
COMMENT ON TABLE countries IS 'Tabela com países e seus códigos de bandeira SVG';
COMMENT ON COLUMN countries.name IS 'Nome do país em inglês';
COMMENT ON COLUMN countries.flag_code IS 'Código ISO da bandeira (ex: us, br, gb-eng)';
COMMENT ON COLUMN countries.flag_svg IS 'Conteúdo SVG da bandeira (opcional, pode ser carregado depois)';

-- Exemplo de consulta para testar
-- SELECT name, flag_code FROM countries WHERE name LIKE '%Brazil%'; 